Convert ostree_boot_image task to a container
The artifact.ci.centos.org forwarding should be done with a
proper http proxy instead.  But this works now.

diff --git a/tasks/ostree-boot-image b/tasks/ostree-boot-image
--- a/tasks/ostree-boot-image
+++ b/tasks/ostree-boot-image
@@ -1,10 +1,23 @@
 #!/bin/sh
 
-set -x
+set -xe
 env
 
 # Find the base dir
 base_dir="$(dirname $0)/.."
+HOMEDIR=$(pwd)
+
+function clean_up {
+    set +e
+    # Tear down the atomic host and image
+    sudo docker run --privileged -it --link libvirtd:libvirtd -e commit=${commit} -e image2boot=${image2boot} -e state=absent -v /var/lib/libvirt/:/var/lib/libvirt/ -v ${HOMEDIR}/output/:/root/output/ -v ${basedir}/:/root/ci-pipeline ostree_boot_image
+
+    # Kill our libvirtd docker instance.
+    #  We can change this in the future to have it stick around if needed
+    sudo docker kill libvirtd
+    sudo docker rm libvirtd
+}
+trap clean_up EXIT SIGHUP SIGINT SIGTERM
 
 if [ "${branch}" = "master" -o "${branch}" = "rawhide" ]; then
     branch="rawhide"
@@ -13,106 +26,39 @@ else
     VERSION=$(echo $branch | sed -e 's/[a-zA-Z]*//')
 fi
 
-export ara_location=$(python -c "import os,ara; print(os.path.dirname(ara.__file__))")
-export ANSIBLE_CALLBACK_PLUGINS=$ara_location/plugins/callbacks
-export ANSIBLE_ACTION_PLUGINS=$ara_location/plugins/actions
-export ANSIBLE_LIBRARY=$ara_location/plugins/modules
-
-
-REF="fedora/${branch}/x86_64/atomic-host"
-
-mkdir -p logs
-
-for v in images; do
-    rsync --delete --stats -a ${RSYNC_USER}@${RSYNC_SERVER}::${RSYNC_DIR}/${branch}/${v}/ ${v}/
-done
-
-currentdir=$(pwd)
-
-# Create directory for temporary files
-tmpdir=$(mktemp -d)
-
-# Kill backgrounded jobs on exit
-function clean_up {
-    ansible-playbook -i hosts ci-pipeline/playbooks/setup-libvirt-image.yml -l ostree_compose_slave_baremetal -e 'state=absent'
-    kill $(jobs -p)
-    sudo rm -rf $tmpdir
-    ara generate junit - > $currentdir/logs/ansible_xunit.xml
-    rm -rf $HOME/.ara
-    cp -rp $currentdir/packagevolume/artifacts $currentdir/logs
-    rm -rf $currentdir/packagevolume
-}
-trap clean_up EXIT SIGHUP SIGINT SIGTERM
-
-if [ -d "images" ]; then
-    if [ -d "images/latest-atomic.qcow2" ]; then
-        # Use symlink if it exists
-        IMG_URL="${HTTP_BASE}/${branch}/images/latest-atomic.qcow2"
-    else
-        # Find the last image we pushed
-        prev_img=$(ls -tr images/*.qcow2 | tail -n 1)
-        IMG_URL="${HTTP_BASE}/${branch}/$prev_img"
-    fi
+# Make sure logs are empty so we don't report previous build
+# if we fail
+if [ -e "${HOMEDIR}/output/logs" ]; then
+    sudo rm -rf ${HOMEDIR}/output/logs >/dev/null 2>&1
+    echo "rm -rf ${HOMEDIR}/output/logs rc:$?"
 fi
+mkdir -p ${HOMEDIR}/output
 
-# If image2boot is defined use that image, but if not fall back to the
-# previous image built
-bootimage=${image2boot:-$IMG_URL}
+pushd $base_dir/config/Dockerfiles/rsync
+sudo docker build -t rsync-container .
+popd
 
-if ! [ -f ~/.ssh/id_rsa ]; then
-    ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
-    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
-fi
+pushd $base_dir/config/Dockerfiles/libvirtd
+sudo docker build --build-arg OSTREE_REPO_SERVER=artifacts.ci.centos.org -t libvirtd .
+popd
 
-pubkey=$(cat ~/.ssh/id_rsa.pub)
+pushd $base_dir/config/Dockerfiles/ostree_boot_image
+sudo docker build -t ostree_boot_image .
+popd
 
-mkdir -p host_vars
-cat << 'EOF' > host_vars/ostree_compose_slave_baremetal.yml
-qemu_img_path: /var/lib/libvirt/images
-bridge: virbr0
-libvirt_systems:
- atomic-host-fedoraah:
-   admin_passwd: $5$uX5x24soDWv3G2TH$BYxhEq4HmxjKmyChV0.VTpqxfhqMaRk8LCr34KOg2C7
-   memory: 3072
-   disk: 10G
-EOF
-cat << EOF >> host_vars/ostree_compose_slave_baremetal.yml
-   img_url: $bootimage
-   admin_ssh_rsa: $pubkey
-EOF
-cat << EOF > hosts
-[libvirt-hosts]
-ostree_compose_slave_baremetal ansible_ssh_host=127.0.0.1 ansible_user=builder become=true
-EOF
-# Install net-tools
-sudo yum -y install net-tools
-# Start test VM
-ansible-playbook -i hosts ci-pipeline/playbooks/setup-libvirt-image.yml -l ostree_compose_slave_baremetal -e 'state=present'
+sudo docker run --privileged --cap-add=SYS_ADMIN -v ${HOMEDIR}/output:/home/output -e rsync_paths="images" -e rsync_from="${RSYNC_USER}@${RSYNC_SERVER}::${RSYNC_DIR}/${branch}/" -e rsync_to="/home/output/" -e RSYNC_PASSWORD="$RSYNC_PASSWORD" rsync-container
+echo $?
 
-PROVISION_STATUS=$?
-if [ "$PROVISION_STATUS" != 0 ]; then
-    echo "ERROR: Provisioning\nSTATUS: $PROVISION_STATUS"
-    exit 1
-fi
+sudo docker run --privileged -d \
+-v /var/lib/libvirt/:/var/lib/libvirt/ \
+-v /sys/fs/cgroup:/sys/fs/cgroup:rw --name libvirtd libvirtd
 
-# Get libvirt IP
-IP=$(cat libvirt-hosts | tail -n 1 | cut -d '=' -f 2)
-
-cat << EOF > inventory
-[ostree_compose_slave]
-$IP ansible_user=admin ansible_ssh_pass=admin ansible_become=true ansible_become_pass=admin
-EOF
-
-ansible-playbook -i inventory ci-pipeline/playbooks/ostree-boot-verify.yml -l ostree_compose_slave -e "commit=$commit" -v
-
-BOOT_STATUS=$?
-if [ "$BOOT_STATUS" != 0 ]; then
-    echo "ERROR: Provisioning\nSTATUS: $BOOT_STATUS"
-    exit 1
-fi
+sudo docker run --privileged -it --link libvirtd:libvirtd -e commit=${commit} -e image2boot=${image2boot} -e state=present -v /var/lib/libvirt/:/var/lib/libvirt/ -v ${HOMEDIR}/output/:/root/output/ -v ${basedir}/:/root/ci-pipeline ostree_boot_image
+echo $?
 
 # If image2boot is defined then symlink it as latest
 if [ -n "$image2boot" ]; then
+    pushd ${HOMEDIR}/output/images
     pushd images
     ln -sf $(basename $image2boot) latest-atomic.qcow2
     popd
@@ -120,25 +66,27 @@ if [ -n "$image2boot" ]; then
     for v in images; do
         rsync --delete --stats -a ${v}/ ${RSYNC_USER}@${RSYNC_SERVER}::${RSYNC_DIR}/${branch}/${v}/
     done
+    popd
 fi
 
-# Temporarily put package level test execution here
-pushd ci-pipeline/config/Dockerfiles/package_tests/ansible
-sudo docker build -t package-test .
-popd
+## Temporarily put package level test execution here
+#pushd ci-pipeline/config/Dockerfiles/package_tests/ansible
+#sudo docker build -t package-test .
+#popd
+#
+## Set up mounted volume
+#mkdir $currentdir/packagevolume
+#cp inventory $currentdir/packagevolume
+#cp ~/.ssh/id_rsa $currentdir/packagevolume/ssh_key
+#
+## Run test
+#sudo docker run --privileged -v $currentdir/packagevolume:/tmp -t -e package=${fed_repo} package-test
+#RUNTEST_STATUS=$?
+#if [ "$RUNTEST_STATUS" != 0 ]; then
+#    echo -e "ERROR: RUNTEST\nSTATUS: $RUNTEST_STATUS"
+#    #exit 1
+#    # Still exit 0 so package level testing failure doesnt result in
+#    # sending message saying failed to boot image
+#    exit 0
+#fi
 
-# Set up mounted volume
-mkdir $currentdir/packagevolume
-cp inventory $currentdir/packagevolume
-cp ~/.ssh/id_rsa $currentdir/packagevolume/ssh_key
-
-# Run test
-sudo docker run --privileged -v $currentdir/packagevolume:/tmp -t -e package=${fed_repo} package-test
-RUNTEST_STATUS=$?
-if [ "$RUNTEST_STATUS" != 0 ]; then
-    echo -e "ERROR: RUNTEST\nSTATUS: $RUNTEST_STATUS"
-    #exit 1
-    # Still exit 0 so package level testing failure doesnt result in
-    # sending message saying failed to boot image
-    exit 0
-fi
