Use common builders/publishers for setting up duffy node

diff --git a/jobs/ci-pipeline-defaults.yml b/jobs/ci-pipeline-defaults.yml
--- a/jobs/ci-pipeline-defaults.yml
+++ b/jobs/ci-pipeline-defaults.yml
@@ -70,3 +70,50 @@
           matrix-trigger: only-configurations
           send-to:
             - recipients
+
+- builder:
+    name: ci-pipeline-duffy-builder
+    builders:
+        - macro-cciskel-duffy-prepared-allocate:
+            jobclass: builder
+            duffytimeoutsecs: 3600
+            playbook: {playbook}
+        - shell: |
+            #!/bin/bash
+            set -xeuo pipefail
+
+            (echo -n "export RSYNC_PASSWORD=" && cat ~/duffy.key | cut -c '-13') > rsync-password.sh
+            cat >>task.env <<EOF
+            export BUILD="rawhide"
+            export JENKINS_JOB_NAME="${{JOB_NAME}}"
+            export JENKINS_BUILD_TAG="${{BUILD_TAG}}"
+            export OSTREE_BRANCH="${{OSTREE_BRANCH:-}}"
+            export fed_repo="${{fed_repo}}"
+            export fed_branch="${{fed_branch}}"
+            export fed_rev="${{fed_rev}}"
+            EOF
+            cat task.env
+
+            rsync -Hrlptv --stats -e ssh task.env rsync-password.sh builder@${{DUFFY_HOST}}:${{JOB_NAME}}
+            for repo in ci-pipeline sig-atomic-buildscripts; do
+                rsync -Hrlptv --stats --delete -e ssh $repo/ builder@${{DUFFY_HOST}}:${{JOB_NAME}}/$repo
+            done
+
+            build_success=true
+            if ! ssh -tt builder@${{DUFFY_HOST}} "pushd ${{JOB_NAME}} && . rsync-password.sh && . task.env && ./ci-pipeline/tasks/{task}"; then
+                build_success=false
+            fi
+
+            rsync -Hrlptv --stats -e ssh builder@${{DUFFY_HOST}}:${{JOB_NAME}}/logs/ $WORKSPACE/logs || true
+            # Exit with code from the build
+            if test "${{build_success}}" = "false"; then
+                echo 'Build failed, see logs above'; exit 1
+            fi
+
+- publisher:
+    name: ci-pipeline-duffy-publisher
+    publishers:
+        - archive:
+            artifacts: 'logs/**'
+            allow-empty: 'true'
+        - macro-cciskel-duffy-deallocate
