add make test
Signed-off-by: Johnny Bieren <jbieren@redhat.com>

diff --git a/jobs/test.yaml b/jobs/test.yaml
--- a/jobs/test.yaml
+++ b/jobs/test.yaml
@@ -49,7 +49,8 @@
            command: build.description = build.getEnvironment().get('fed_repo')
         - shell: |
             # Need to test to make sure fedpkg rpm is installed
-            # TODO
+            which fedpkg
+            if [ "$?" != 0 ]; then echo "ERROR: FEDPKG RPM NOT INSTALLED\nSTATUS: $?"; exit 1; fi
             # Clone the fedoraproject git repo
             fedpkg clone -a $fed_repo
             if [ "$?" != 0 ]; then echo "ERROR: FEDPKG CLONE\nSTATUS: $?"; exit 1; fi
@@ -60,6 +61,24 @@
             git checkout $fed_rev
             # Create new branch because fedpkg wont build with detached head
             git branch -b test_branch
+            # fedpkg prep to unpack the tarball
+            fedpkg --release $fed_branch prep
+            TARBALL=$(find . -maxdepth 1 -name "*tar*")
+            # Make sure we have rpmspec before we call it
+            which rpmspec
+            if [ "$?" != 0 ]; then echo "ERROR: RPMSPEC RPM NOT INSTALLED\nSTATUS: $?"; exit 1; fi
+            VERSION=$(rpmspec --queryformat "${{VERSION}}\n" -q ${{fed_rev}}.spec | head -n 1)
+            pushd ${{fed_rev}}-$VERSION
+            ./configure
+            # Run tests if they are there
+            make test
+            MAKE_TEST_STATUS=$?
+            popd
+            if [ "$MAKE_TEST_STATUS" == 2 ]; then
+                 echo "description='$fed_repo - No tests'" >> ${{WORKSPACE}}/fedmsg_fields.txt
+            else
+                 echo "description=$fed_repo" >> ${{WORKSPACE}}/fedmsg_fields.txt
+            fi
             # Build the package into ./results_$fed_repo/$VERSION/$RELEASE/
             fedpkg --release $fed_branch mockbuild
             if [ "$?" != 0 ]; then echo "ERROR: FEDPKG MOCKBUILD\nSTATUS: $?"; exit 1; fi
@@ -68,6 +87,10 @@
             # TODO: get rest of the rpms and build ostree
             
             exit 0
+        - inject:
+            properties-file: ${{WORKSPACE}}/fedmsg_fields.txt
+        - system-groovy:
+           command: build.description = build.getEnvironment().get('description')
 
     publishers:
       - archive:
